### ISSUE TITLE
Build error using esp-idf version 4

### ISSUE THREAD

**Issue by nopnop2002** [siara-cc/esp32-idf-sqlite3-examples#4]
When building in esp-idf Ver4 environment, the following error occurs.
I issued a PR.

	$ cd esp32-idf-sqlite3-examples/spiffs
	$ make
	Python requirements from /home/nop/esp-idf/requirements.txt are satisfied.
	GENCONFIG
	App "sqlite3_spiffs" version: 653c088-dirty
	CC build/bootloader/bootloader_support/src/bootloader_flash.o
	CC build/bootloader/bootloader_support/src/flash_qio_mode.o
	CC build/bootloader/bootloader_support/src/bootloader_flash_config.o
	CC build/bootloader/bootloader_support/src/bootloader_init.o
	CC build/bootloader/bootloader_support/src/bootloader_common.o
	CC build/bootloader/bootloader_support/src/bootloader_clock.o
	CC build/bootloader/bootloader_support/src/bootloader_random.o
	CC build/bootloader/bootloader_support/src/flash_partitions.o
	CC build/bootloader/bootloader_support/src/esp_image_format.o
	CC build/bootloader/bootloader_support/src/flash_encrypt.o
	CC build/bootloader/bootloader_support/src/bootloader_utility.o
	CC build/bootloader/bootloader_support/src/esp32/secure_boot_signatures.o
	CC build/bootloader/bootloader_support/src/esp32/secure_boot.o
	CC build/bootloader/bootloader_support/src/esp32/bootloader_sha.o
	CC build/bootloader/bootloader_support/src/esp32/flash_encrypt.o
	AR build/bootloader/bootloader_support/libbootloader_support.a
	CC build/bootloader/log/log.o
	AR build/bootloader/log/liblog.a
	CC build/bootloader/spi_flash/spi_flash_rom_patch.o
	AR build/bootloader/spi_flash/libspi_flash.a
	CC build/bootloader/micro-ecc/micro-ecc/uECC.o
	AR build/bootloader/micro-ecc/libmicro-ecc.a
	CC build/bootloader/soc/esp32/rtc_pm.o
	CC build/bootloader/soc/esp32/rtc_periph.o
	CC build/bootloader/soc/esp32/cpu_util.o
	CC build/bootloader/soc/esp32/sdmmc_periph.o
	CC build/bootloader/soc/esp32/rtc_wdt.o
	CC build/bootloader/soc/esp32/soc_memory_layout.o
	CC build/bootloader/soc/esp32/sdio_slave_periph.o
	CC build/bootloader/soc/esp32/rtc_time.o
	CC build/bootloader/soc/esp32/spi_periph.o
	CC build/bootloader/soc/esp32/rtc_init.o
	CC build/bootloader/soc/esp32/rtc_clk_init.o
	CC build/bootloader/soc/esp32/gpio_periph.o
	CC build/bootloader/soc/esp32/rtc_sleep.o
	CC build/bootloader/soc/esp32/rtc_clk.o
	CC build/bootloader/soc/esp32/emac_hal.o
	CC build/bootloader/soc/src/lldesc.o
	CC build/bootloader/soc/src/memory_layout_utils.o
	CC build/bootloader/soc/src/soc_include_legacy_warn.o
	CC build/bootloader/soc/src/hal/spi_slave_hal_iram.o
	CC build/bootloader/soc/src/hal/spi_slave_hal.o
	CC build/bootloader/soc/src/hal/spi_flash_hal_iram.o
	CC build/bootloader/soc/src/hal/spi_flash_hal.o
	CC build/bootloader/soc/src/hal/spi_hal_iram.o
	CC build/bootloader/soc/src/hal/spi_hal.o
	AR build/bootloader/soc/libsoc.a
	CC build/bootloader/main/bootloader_start.o
	AR build/bootloader/main/libmain.a
	CC build/bootloader/efuse/esp32/esp_efuse_table.o
	CC build/bootloader/efuse/src/esp_efuse_api.o
	CC build/bootloader/efuse/src/esp_efuse_utility.o
	CC build/bootloader/efuse/src/esp_efuse_fields.o
	AR build/bootloader/efuse/libefuse.a
	LD build/bootloader/bootloader.elf
	Pyserial is not installed for /usr/bin/python3. Check the README for installation instructions.
	Traceback (most recent call last):
	  File "/home/nop/esp-idf/components/esptool_py/esptool/esptool.py", line 37, in <module>
	    import serial
	ModuleNotFoundError: No module named 'serial'
	/home/nop/esp-idf/components/esptool_py/Makefile.projbuild:72: recipe for target '/home/nop/esp32-idf-sqlite3-examples/spiffs/build/bootloader/bootloader.bin' failed
	make[1]: *** [/home/nop/esp32-idf-sqlite3-examples/spiffs/build/bootloader/bootloader.bin] Error 1
	/home/nop/esp-idf/components/bootloader/Makefile.projbuild:41: recipe for target '/home/nop/esp32-idf-sqlite3-examples/spiffs/build/bootloader/bootloader.bin' failed
	make: *** [/home/nop/esp32-idf-sqlite3-examples/spiffs/build/bootloader/bootloader.bin] Error 2

**Comment by siara-cc** [comment]
Hi, Thank you for reporting it.  Please allow me some time to go through your PR before merging it. There are two of them?
In the meanwhile, I would like you to look into my newer repository that has more advantages with memory consumption and speed: https://github.com/siara-cc/sqlite_micro_logger_arduino
I intend to make an esp-idf version of it.

**Comment by siara-cc** [comment]
Hi, thank you for the PR. I have merged it.
